Repository HiroKX/planifecation, pull requests merged in 2023-12, with the labels that each got.

#59 Fix : Suppression d'un utilisateur
  Serveur/dist/index.js
  Serveur/src/index.ts
Labels: bug

#80 Fix : gitignore pour l'environement de prod
  Serveur/.gitignore
  Serveur/dist/index.js
Labels: enhancement

#91 65 je veux un agenda sur mon application
  Application/.env
  Application/App.tsx
  Application/package.json
  Application/src/components/atoms/AppTemplate.tsx
  Application/src/components/atoms/styles/ButtonTemplate.tsx
  Application/src/components/atoms/styles/TextInputTemplate.tsx
  Application/src/components/atoms/styles/TextTemplate.tsx
  Application/src/components/molecules/ColorPickerTemplate.tsx
  Application/src/components/molecules/SurfaceTemplate.tsx
  Application/src/components/molecules/TabScreenTemplate.tsx
  Application/src/components/organisms/CalendarTemplate.tsx
  Application/src/components/organisms/EventDetails.tsx
  Application/src/components/organisms/ModalTemplate.tsx
  Application/src/components/organisms/OwnPaperProvider.tsx
  Application/src/components/organisms/TabsTemplate.tsx
  Application/src/components/organisms/TimelineTemplate.tsx
  Application/src/components/pages/Agenda.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Home.tsx
  Application/src/components/pages/Login.tsx
  Application/src/components/pages/Profile.tsx
  Application/src/components/pages/Settings.tsx
  Application/src/components/pages/SignUp.tsx
  Application/src/components/pages/ThemeSandbox.tsx
  Application/src/environment/darktheme.tsx
  Application/src/environment/lightTheme.ts
  Application/src/environment/locale.ts
  Application/src/models/User.ts
  Application/src/navigation/RootStack.tsx
  Application/src/services/utils/utils.ts
  Application/src/store/EventsSlice.tsx
Labels: front

#97 96 je veux un splash screen au moment douvrir notre application
  Application/App.tsx
  Application/src/components/atoms/styles/LogoTemplate.tsx
  Application/src/components/pages/Splashscreen.tsx
Labels: front

#94 69 je veux un menu qui liste mes notes de bloc notes
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Notes/Notepad.tsx
  Application/src/controllers/NoteController.tsx
  Application/src/controllers/UserController.tsx
  Application/src/models/Note.ts
  Application/src/navigation/RootStack.tsx
  Application/src/services/NoteService.tsx
  Application/src/services/UserService.tsx
Labels: bug, front

#93 75 je veux une to do list sur mon application
  Application/src/components/molecules/CheckboxTemplate.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Todo.tsx
  Application/src/models/Todo.ts
  Application/src/navigation/RootStack.tsx
Labels: front

#103 Fix Todo
  Application/src/components/pages/TodoList.tsx
Labels: bug
