Repository HiroKX/planifecation, pull requests merged in 2023-11, with the labels that each got.

#32 Refactor : Modification de la structure, des templates et de la navigation
  Application/App.tsx
  Application/package.json
  Application/src/components/AppTemplate.tsx
  Application/src/components/atoms/ButtonTemplate.tsx
  Application/src/components/atoms/TextInputTemplate.tsx
  Application/src/components/atoms/sso/GoogleButton.tsx
  Application/src/components/organisms/SurfaceTemplate.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Home.tsx
  Application/src/components/pages/Login.tsx
  Application/src/components/pages/SignUp.tsx
  Application/src/components/sso/GoogleUp.tsx
  Application/src/components/templates/ButtonTemplate.tsx
  Application/src/components/templates/CardTemplate.tsx
  Application/src/components/templates/SurfaceTemplate.tsx
  Application/src/components/templates/TextInputTemplate.tsx
  Application/src/controllers/sso/GoogleAuth.tsx
  Application/src/environment/Global_variable.tsx
  Application/src/models/User.tsx
  Application/src/navigation/RootStack.tsx
Labels: refacto

#33 Fix : templates with their children props
  Application/src/components/atoms/ButtonTemplate.tsx
  Application/src/components/atoms/TextInputTemplate.tsx
  Application/src/components/organisms/SurfaceTemplate.tsx
Labels: bug

#34 Fixed properly props in templates
  Application/src/components/atoms/ButtonTemplate.tsx
  Application/src/components/atoms/TextInputTemplate.tsx
  Application/src/components/organisms/SurfaceTemplate.tsx
  Application/src/components/pages/Home.tsx
Labels: bug

#36 Ajout de coding standards (Analyse statique)
  Application/.babelrc
  Application/.prettierignore
  Application/.prettierrc
  Application/App.tsx
  Application/README.md
  Application/app.config.ts
  Application/app.json
  Application/babel.config.js
  Application/package.json
  Application/src/components/AppTemplate.tsx
  Application/src/components/atoms/SettingsButton.tsx
  Application/src/components/atoms/sso/GoogleButton.tsx
  Application/src/components/atoms/styles/ButtonTemplate.tsx
  Application/src/components/atoms/styles/TextInputTemplate.tsx
  Application/src/components/organisms/SurfaceTemplate.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Home.tsx
  Application/src/components/pages/Login.tsx
  Application/src/components/pages/Settings.tsx
  Application/src/components/pages/SignUp.tsx
  Application/src/controllers/sso/GoogleAuth.tsx
  Application/src/environment/themes.tsx
  Application/src/models/User.tsx
  Application/src/navigation/RootStack.tsx
  Application/src/services/AuthenticationService.tsx
  Application/src/services/LogoService.tsx
  Application/src/services/SnackBarService.tsx
Labels: enhancement

#40 Refonte pour bien afficher le slide toggle + prettier de tout le projet
  Application/README.md
  Application/src/components/organisms/SurfaceTemplate.tsx
  Application/src/components/pages/Settings.tsx
Labels: front
