Repository HiroKX/planifecation, pull requests merged in 2024-01, with the labels that each got.

#107 Fix Navigator pour ToDo
  Application/src/navigation/RootStack.tsx
Labels: bug

#109 108 je veux pouvoir lancer mon projet rapidement
  Application/README.md
  README.md
  Serveur/README.md
Labels: documentation

#114 update CheckboxTemplate
  Application/src/components/molecules/CheckboxTemplate.tsx
Labels: enhancement, front

#126 125 ajout requêtes graphql agenda
  Serveur/prisma/schema.prisma
  Serveur/src/index.ts
  Serveur/src/mutation/AgendaMutations.ts
  Serveur/src/mutation/NoteMutations.ts
  Serveur/src/mutation/ToDoMutations.ts
  Serveur/src/mutation/UserMutations.ts
  Serveur/src/queries/AgendaQueries.ts
  Serveur/src/types/TypeDefs.ts
Labels: back

#120 Ajout de vérifications sur les formulaires
  .github/workflows/ci_check_prettier.yml
  .github/workflows/ci_graphql.yml
  .github/workflows/ci_test.yml
  Application/package.json
  Application/src/components/atoms/styles/PasswordConfirmInput.tsx
  Application/src/components/atoms/styles/PasswordInput.tsx
  Application/src/components/atoms/styles/UsernameInput.tsx
  Application/src/components/pages/Login.tsx
  Application/src/components/pages/Profile.tsx
  Application/src/components/pages/Security/Login.tsx
  Application/src/components/pages/Security/SignUp.tsx
  Application/src/components/pages/SignUp.tsx
  Application/src/components/pages/User/Profile.tsx
  Application/src/components/pages/User/Settings.tsx
  Application/src/controllers/AuthenticationController.tsx
  Application/src/controllers/UserController.tsx
  Application/src/navigation/RootStack.tsx
  Application/src/services/AuthenticationService.tsx
  Application/src/services/__tests__/AuthenticationService.test.tsx
Labels: enhancement

#133 132 je veux pouvoir diter facilement mes notes
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Notes/Notepad.tsx
  Application/src/controllers/NoteController.tsx
  Application/src/navigation/RootStack.tsx
  Application/src/services/NoteService.tsx
  Application/tsconfig.json
  Serveur/tsconfig.json
Labels: front

#141 123 je veux que le chargement de mes tâches et mes notes soient triées plus logiquement
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Notes/Notepad.tsx
  Application/src/components/pages/Todo/CheckTodo.tsx
  Application/src/components/pages/Todo/TodoList.tsx
  Application/src/models/Todo.ts
  Application/tsconfig.json
  Serveur/tsconfig.json
Labels: enhancement, front

#142 101 je veux que mon agenda prenne moins de temps à charger
  Application/App.tsx
  Application/package.json
  Application/src/components/atoms/AppTemplate.tsx
  Application/src/components/molecules/ColorPickerTemplate.tsx
  Application/src/components/molecules/TabScreenTemplate.tsx
  Application/src/components/organisms/CalendarTemplate.tsx
  Application/src/components/organisms/EventDetails.tsx
  Application/src/components/organisms/TabsTemplate.tsx
  Application/src/components/organisms/TimelineTemplate.tsx
  Application/src/components/pages/Agenda.tsx
  Application/src/components/pages/Agenda/AgendaEventDetails.tsx
  Application/src/components/pages/Agenda/Appointments.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/controllers/AgendaController.tsx
  Application/src/environment/locale.ts
  Application/src/environment/themes.tsx.old
  Application/src/models/AgendaEvent.ts
  Application/src/navigation/RootStack.tsx
  Application/src/services/AgendaService.tsx
  Application/src/services/utils/utils.ts
  Application/src/store/EventsSlice.tsx
  Serveur/package.json
Labels: enhancement, refacto, back, front

#143 140 je veux pouvoir tester le gyroscope du tlphone sur une page de test
  Application/package.json
  Application/src/components/organisms/GyroscopTest.tsx
  Application/src/components/pages/Home.tsx
  Application/src/navigation/RootStack.tsx
Labels: enhancement, front
