Repository HiroKX/planifecation, pull requests merged in 2024-03, with the labels that each got.

#162 158 je veux un impact ngatif sur les performances de lapplication pour quelquun qui souhaiterait la rendre meilleure
  Application/package.json
  Application/src/components/atoms/styles/GraphicTextTemplate
  Application/src/components/atoms/styles/SliderTemplate.tsx
  Application/src/components/pages/Agenda/Appointments.tsx
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Todo/TodoList.tsx
  Application/src/components/pages/User/Settings.tsx
  Application/src/services/utils/utils.ts
Labels: enhancement, refacto, front

#152 144 fix agenda
  Application/src/components/organisms/EventDetails.tsx
  Application/src/components/pages/Agenda/AgendaTemplate.tsx
  Application/src/components/pages/Agenda/Appointments.tsx
  Application/src/components/pages/Agenda/CalendarTemplate.tsx
  Application/src/components/pages/Agenda/EventTemplate.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/navigation/RootStack.tsx
Labels: bug

#166 165 refonte visuelle splashscreen accueil connexion inscription
  Application/App.tsx
  Application/src/components/atoms/styles/ButtonTemplate.tsx
  Application/src/components/atoms/styles/LogoTemplate.tsx
  Application/src/components/atoms/styles/PasswordConfirmInput.tsx
  Application/src/components/atoms/styles/PasswordInput.tsx
  Application/src/components/atoms/styles/TextInputTemplate.tsx
  Application/src/components/atoms/styles/UsernameInput.tsx
  Application/src/components/molecules/SurfaceTemplate.tsx
  Application/src/components/organisms/OwnPaperProvider.tsx
  Application/src/components/pages/Home.tsx
  Application/src/components/pages/Security/Login.tsx
  Application/src/components/pages/Security/SignUp.tsx
  Application/src/components/pages/Splashscreen.tsx
  Application/src/navigation/RootStack.tsx
Labels: enhancement, refacto, front

#164 163 je veux pouvoir choisir les dates de mes events plus facilement
  Application/package.json
  Application/src/components/molecules/IconButtonTemplate.tsx
  Application/src/components/organisms/ModalTemplate.tsx
  Application/src/components/pages/Agenda/Appointments.tsx
  Application/src/components/pages/Agenda/EventTemplate.tsx
  Application/src/services/utils/utils.ts
Labels: enhancement, front

#178 159 je veux une refonte de lui pour quelle soit plus jolie
  Application/src/components/atoms/AppTemplate.tsx
  Application/src/components/atoms/styles/ButtonTemplate.tsx
  Application/src/components/atoms/styles/KeyboardButton.tsx
  Application/src/components/atoms/styles/SliderTemplate.tsx
  Application/src/components/atoms/styles/TextInputTemplate.tsx
  Application/src/components/molecules/CheckboxTemplate.tsx
  Application/src/components/molecules/SurfaceTemplate.tsx
  Application/src/components/organisms/OwnPaperProvider.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Notes/Notepad.tsx
  Application/src/components/pages/Notes/keyboard/VirtualRandomKeyboard.tsx
  Application/src/components/pages/Todo/TodoList.tsx
  Application/src/components/pages/User/Profile.tsx
  Application/src/components/pages/User/Settings.tsx
  Application/src/services/utils/utils.ts
Labels: enhancement, refacto, front

#189 Ajout du CGU + modif Paramètres
  Application/src/assets/cgu.ts
  Application/src/components/molecules/SurfaceTemplate.tsx
  Application/src/components/pages/Cgu.tsx
  Application/src/components/pages/User/Settings.tsx
  Application/src/navigation/RootStack.tsx
Labels: front

#191 Haptics un peu partout + quelques fixs
  Application/src/components/atoms/SettingsButton.tsx
  Application/src/components/pages/Dashboard.tsx
  Application/src/components/pages/Home.tsx
  Application/src/components/pages/Notes/NoteList.tsx
  Application/src/components/pages/Notes/keyboard/VirtualRandomKeyboard.tsx
  Application/src/components/pages/Todo/TodoList.tsx
Labels: enhancement, front
